# Generated by Django 2.2.1 on 2019-06-06 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('edition', models.CharField(max_length=30)),
                ('author', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Library_App.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Bookinstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique Id for the book for the entire library', primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_modified', models.DateField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Library_App.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_lock', models.IntegerField()),
                ('book_instance_id', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Library_App.Bookinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.CharField(help_text='Enter a book Genre(e.g Science,Fiction,Non-Fiction)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(help_text='Enter a book Language', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Enter Whether Loan or Purchase', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('book_instance_id', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Library_App.Bookinstance')),
                ('borrow_id', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Library_App.Borrow_Detail')),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.Fine')),
                ('user_id', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='borrow_detail',
            name='fine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_App.Fine'),
        ),
        migrations.AddField(
            model_name='borrow_detail',
            name='user_id',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Library_App.Language'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='purchase_type',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Library_App.Purchase_Type'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Enter a book Genre(e.g Science,Fiction,Non-Fiction)', on_delete=django.db.models.deletion.CASCADE, to='Library_App.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Library_App.Publisher'),
        ),
    ]
